= Laplacien
:author: ESCHBACH Simon
:stem: latexmath
:icons: font
:toc: left


Soit stem:[\Omega] un domaine régulier et ouvert de stem:[\mathbb{R}^2]. 
On décompose sa frontière en trois partie stem:[\partial\Omega=\Gamma_{D}\cup\Gamma_{N}\cup\Gamma_{R}] qui ne s'intersecte pas.
Sur ce domaine, on pose l'équation diférenciel suivante:

.equation du laplacien
[stem]
++++
\left\{
\begin{aligned}
-\Delta u=f &\quad u\in \Omega; \\
u=g_{D} &\quad u\in \Gamma_{D};\\
\frac{\partial u}{\partial n}=g_{N} &\quad u\in \Gamma_{N};\\
au+\frac{\partial u}{\partial n}=g_{R} &\quad u\in \Gamma_{R}.\\
\end{aligned}
\right.
++++


Pour cela, on essaie de se ramener a la formulation variationnelle et donc récuperer une solution faible.
Pour cela, on multiplie par une fonction test stem:[\phi] puis on intègre sur stem:[\Omega]
( le choix de l'espace où vit la fonction test sera déterminer lorsqu'on aura la formulation variationnelle).
On obtient donc l'équation suivante:

[stem]
++++
\int_\Omega -\Delta u(t)\phi(t)dt=
\int_\Omega f(t)\phi(t)dt
++++

Pour des question de lisibilité, on n'écrira plus stem:[dt] et stem:[t].
On peut appliquer la formule de Green sur la première intégrale.
On obtient alors la formule suivante :

.formulation variationnelle
[stem]
++++
-\int_{\partial\Omega} \frac{\partial u}{\partial n}\phi+
\int_{\Omega} \nabla u\nabla\phi=
\int_\Omega f\phi
++++




On va d'abord commencer par traiter les cas où il n'y a qu'une partie pour la frontière de stem:[\Omega]( les deux autres seront vides)

== Condition de Dirichlet ou essentiel

include::dirichlet.adoc[]

== Condition de Neuman ou naturel

include::neuman.adoc[]

== Condition de Robin, Fourier ou Mixte

include::robin.adoc[]


